GET http://localhost:3333/
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlZjBkNGE3Yi03MDc5LTQzNWYtYWY5OC03YTk3ZmM2NDQ5OGQiLCJpYXQiOjE3Mjg0MDk5MjIsImV4cCI6MTcyOTAxNDcyMn0.uhoGTqFKe_GgprJ6HJj3qhV6LpjjuFQ2H-dkJ6BUS9I